name: Showcase
on:
  push:
    branches:
      - master
env:
  SHOWCASE_ENV: lol
jobs:
  build:
    name: TODO
    runs-on: ubuntu-latest
    steps:
      - id: command
        run: echo ${{ env.SHOWCASE_ENV }}
      - id: env-pipeline
        name: show-pipeline-environemnt
        run: ls
