name: Showcase
on:
  push:
    branches:
      - master
env:
  SHOWCASE_ENV: lol
jobs:
  build:
    name: TODO
    runs-on: ubuntu-latest
    steps:
      - id: command
        run: echo ${{ env.SHOWCASE_ENV }}
      - id: env-pipeline
        name: show-pipeline-environemnt
        run: ls
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run lint
      - run: npm test
  containerizing:
    name: DockerPush
    runs-on: ubuntu-latest
    steps:
      - run: docker login -u sanjay67890 -p "$DOCKER_SECRET"
        env:
          DOCKER_SECRET: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: docker tag first:0.0.3 sanjay67890/first:0.0.3
      - run: docker push sanjay67890/first:0.0.3
        

# https://github.com/marketplace/actions/setup-docker
# needed to make it repo secret ipv env secret: https://damienaicheh.github.io/github/actions/2021/04/15/environment-variables-secrets-github-actions-en.html